Mekurun/mekurun.com

_layouts/category.html
index.markdown

close https://github.com/Mekurun/mekurun.com/issues/60
難易度のアイコンを変更し、色でわけました

Change colors diff

---

_layouts/course.html

クエリでページ設定できるようにした

---

_layouts/course.html

const も varにした(ES6の構文は使えないので)

---

_i18n/en.yml
_i18n/ja.yml
_i18n/kana.yml
_includes/footer.html
_layouts/default.html
about.md
contact.md
faq.md
index.markdown
news.md
privacy.md
projects.md
term-of-use.md
tips.md
usage.md

close https://github.com/Mekurun/mekurun.com/issues/66
- 英語と日本語のdescriptionを書く

すたてぃっくページの説明を多言語対応

---

_config.yml

- `Uglifier::Error` が出ないように修正
<https://github.com/digitalsparky/jekyll-minifier>

Uglifier::Error が出ないように修正

---

src/js/course.js

- close #153 
- 数字以外の page クエリが指定されたらそのクエリを削除するように変更。

数字以外の page クエリが指定されたらそのクエリを削除するように変更。

---

_includes/course-list.html
_layouts/category.html

close https://github.com/Mekurun/mekurun.com/issues/107
英語、日本語、ひらがなの表示で確認しました。

その難易度のコースが存在しないときに難易度の見出しを非表示にする

---

_layouts/course.html
css/main.scss

リファクタリングしました。
Labelだけ左に4pxのmarginがあって他の要素と揃っていなかったのでmargin-topだけ指定
レビュー&マージお願いします〜。

Fix label style

---

_layouts/course.html

- PDFボタンを押したときの確認アラートを削除
- PDFを直リンクにして新しいタブで開くようにする
レビュー&マージお願いします〜。
(これぐらいならコード見たら自分でもできたわ)

Remove confirm alert

---

vercel.json

トレイリングスラッシュをありに統一する

---

vercel.json

vercel.jsonを一部変更

---

_layouts/default.html

Twitterタイトルの修正

---

_layouts/post.html

記事ページに支援のお願いを追加

---

_i18n/ja/about.md

のざゆきのアイコンパス設定修正

---

_sass/main.scss

サブカラーを#fe9161に決定した

---

_includes/header.html
_sass/main.scss
service-worker.js

ヘッダーのボタンの幅調整

---

_sass/main.scss

ボタンの幅本番環境修正

---

_layouts/default.html
_sass/main.scss

`font-weight: 500` に設定していた部分にやっと太さが適用されたため、雰囲気が変わりました。雰囲気を大幅に変更しないために一旦400に戻すのもありかな

フォントを "Noto Sans JP" に変更

---

_layouts/default.html
_sass/main.scss
index.markdown
service-worker.js

close https://github.com/Mekurun/mekurun.com/issues/243
- xx
- xx

フォントの変更・最新のコースの表示変更

---

_sass/main.scss
courses.md
css/courses.scss
service-worker.js

コース一覧ページのデザイン修正・改善

---

css/courses.scss

コース一覧ページデザイン修正

---

_layouts/default.html
_sass/main.scss

フォント読み込み絶対パスに変更

---

_data/supporter.yml

ご支援者様お名前掲載

---

_layouts/default.html

fontawesome、preload
